[colors.normal]
black = "0x282c34"
cyan = "0x666666"
green = "0x98be65"
magenta = "0xc678dd"
red = "0xff6c6b"
white = "0xbbc2cf"
yellow = "0xecbe7b"

[colors.primary]
background = "0x1f2329"
foreground = "0xbbc2cf"
