import = ["/home/vish/.config/alacritty/themes/themes/doom_one.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}\t"

[window]
opacity = 0.85

[window.padding]
x = 0
y = 0
